'use client';
import {useEffect,useState,useRef} from 'react';
import {labels,type Section} from '@/lib/contracts';
type Grant={grant_id:string;clinician_name:string;sections:Section[];issued_at:string;expires_at:string;revoked_at:string|null;status:string};
type Event={id:string;grant_id:string;actor_name:string|null;action:string;outcome:string;sections:Section[];occurred_at:string};
export default function Access(){
 const [grants,setGrants]=useState<Grant[]>([]),[events,setEvents]=useState<Event[]>([]),[message,setMessage]=useState('Loading access...'),[busy,setBusy]=useState(''),[more,setMore]=useState(false);
 const version=useRef(0);
 async function refresh(signal?:AbortSignal){const current=++version.current;try{const [g,e]=await Promise.all([fetch('/api/grants',{cache:'no-store',signal}),fetch('/api/access-events',{cache:'no-store',signal})]);if(!g.ok||!e.ok)throw Error();const [gd,ed]=await Promise.all([g.json(),e.json()]);if(current!==version.current||signal?.aborted)return;setGrants(gd.grants);setEvents(ed.events);setMore(ed.events.length===50);setMessage('');}catch{if(!signal?.aborted&&current===version.current){setGrants([]);setEvents([]);setMessage('Access details unavailable. Sign in again or retry.');}}}
 useEffect(()=>{const c=new AbortController();refresh(c.signal);const t=setInterval(()=>refresh(c.signal),10000);return()=>{c.abort();clearInterval(t);};},[]);
 async function revoke(id:string){++version.current;setBusy(id);setMessage('Stopping future access...');try{const r=await fetch(`/api/grants/${id}/revoke`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}',cache:'no-store'});if(!r.ok)throw Error();await refresh();setMessage('Revoked. Future server reads are denied.');}catch{setMessage('Revocation could not be confirmed. Retry or check your session.');}finally{setBusy('');}}
 async function older(){if(!events.length)return;setBusy('history');try{const r=await fetch(`/api/access-events?before=${events[events.length-1].id}`,{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();setEvents(es=>[...es,...d.events]);setMore(d.events.length===50);}catch{setMessage('Older history could not be loaded.');}finally{setBusy('');}}
 return <article className="panel access-panel"><h2>Access &amp; history</h2><p>Revoke stops future access. It cannot recall screenshots, memory or copies already taken. An open clinician view clears at its next server check.</p><button className="secondary" disabled={!!busy} onClick={()=>refresh()}>Refresh access</button><p role="status">{message}</p><h3>Recent grants</h3>{!grants.length&&<p>No grants to show.</p>}{grants.map(g=><div className="entry" key={g.grant_id}><h3>{g.clinician_name}</h3><p>{g.sections.map(s=>labels[s]).join(', ')} · {g.status}<br/>Expires {new Date(g.expires_at).toLocaleString()}</p>{g.status==='active'&&<button disabled={!!busy} onClick={()=>revoke(g.grant_id)}>{busy===g.grant_id?'Revoking...':'Revoke now - stops future access'}</button>}{g.revoked_at&&<p>Revoked {new Date(g.revoked_at).toLocaleString()}</p>}</div>)}<h3>Access history</h3><p>Newest first. Fixed action/outcome metadata only; no record values or QR tokens. Up to 50 events per page.</p>{!events.length&&<p>No events to show.</p>}<ol className="audit-list">{events.map(e=><li key={e.id}><strong>{e.actor_name||'Signed-in account'} · {e.action} · {e.outcome}</strong><br/><time dateTime={e.occurred_at}>{new Date(e.occurred_at).toLocaleString()}</time>{e.sections.length>0&&<p>{e.sections.map(s=>labels[s]).join(', ')}</p>}</li>)}</ol>{more&&<button className="secondary" disabled={!!busy} onClick={older}>Load older events</button>}</article>;
}
