'use client';
import {useEffect,useState} from 'react';
import {sections, labels, type Section, type RecordValue} from '@/lib/contracts';
function SectionEditor({section}:{section:Section}) {
  const [value,setValue]=useState<RecordValue>({entries:[]}),[status,setStatus]=useState('Loading...'),[ready,setReady]=useState(false),[busy,setBusy]=useState(false);
  useEffect(()=>{ const controller=new AbortController(); fetch(`/api/records/${section}`,{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok) throw Error(); return r.json();}).then(d=>{setValue(d.record.value);setStatus('');setReady(true);}).catch(()=>{if(!controller.signal.aborted) {setValue({entries:[]});setStatus('Unable to load. Sign in again or retry.');}});return()=>controller.abort();},[section]);
  async function save(){setBusy(true);setStatus('Saving...');try{const r=await fetch(`/api/records/${section}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value),cache:'no-store'});if(!r.ok) {if(r.status===401||r.status===403){setValue({entries:[]});setReady(false);}throw Error();}setStatus('Saved.');}catch{setStatus('Not saved. Check your session and connection.');}finally{setBusy(false);}}
  return <article className="panel"><h2>{labels[section]}</h2>{ready && value.entries.length===0 && <p>No entries yet.</p>}{ready && value.entries.map((entry,i)=><div key={i} className="entry"><label>{labels[section]} item {i+1}<input maxLength={120} value={entry.label} onChange={e=>setValue({entries:value.entries.map((v,j)=>j===i?{...v,label:e.target.value}:v)})}/></label><label>Details<textarea maxLength={500} value={entry.detail} onChange={e=>setValue({entries:value.entries.map((v,j)=>j===i?{...v,detail:e.target.value}:v)})}/></label><button className="secondary" onClick={()=>setValue({entries:value.entries.filter((_,j)=>j!==i)})}>Remove item {i+1}</button></div>)}<div className="row"><button className="secondary" disabled={!ready||busy||value.entries.length>=30} onClick={()=>setValue({entries:[...value.entries,{label:'',detail:''}]})}>Add item</button><button disabled={!ready||busy} onClick={save}>Save {labels[section].toLowerCase()}</button></div><p role="status">{status}</p></article>;
}
export default function Editor(){return <>{sections.map(s=><SectionEditor key={s} section={s}/>)}</>;}
