'use client';
import {useState,useEffect} from 'react';
import QRCode from 'qrcode';
import {sections,labels,type Section} from '@/lib/contracts';
type Grant={grant_id:string;patient_id:string;sections:Section[];expires_at:string;status:string};
type Pending={id:string;token:string;expires_at:string;sections:Section[];status:string;clinician_name?:string;grant?:Grant};
export default function Share(){
 const [selected,setSelected]=useState<Section[]>(['allergies','medicines']),[pending,setPending]=useState<Pending|null>(null),[image,setImage]=useState(''),[message,setMessage]=useState(''),[seconds,setSeconds]=useState(0),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!pending)return;const timer=setInterval(()=>setSeconds(Math.max(0,Math.ceil((Date.parse(pending.expires_at)-Date.now())/1000))),1000);const poll=setInterval(async()=>{try{const r=await fetch(`/api/qr-requests/${pending.id}`,{cache:'no-store'});if(!r.ok){setPending(null);setImage('');setMessage('Request unavailable. Sign in again.');return;}const data=await r.json();setPending(p=>p?.id===data.id?{...p,...data}:p);}catch{setMessage('Network unavailable. No record access has been granted.');}},3000);return()=>{clearInterval(timer);clearInterval(poll);};},[pending?.id]);
 async function approve(){if(!pending)return;setBusy(true);setMessage('Approving...');try{const r=await fetch('/api/grants/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_id:pending.id}),cache:'no-store'});const d=await r.json();if(!r.ok){setMessage('Approval denied. The request may have expired. No new access granted.');return;}setPending(p=>p?{...p,status:'approved',grant:d}:p);setImage('');setMessage('Only these sections are now shared for 10 minutes.');}catch{setMessage('Approval result could not be confirmed. Check request status before retrying.');}finally{setBusy(false);}}
 async function create(){setBusy(true);setPending(null);setImage('');setMessage('Creating...');try{const r=await fetch('/api/qr-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sections:selected}),cache:'no-store'});const d=await r.json();if(!r.ok)throw Error();setPending(d);setSeconds(60);setImage(await QRCode.toDataURL(d.token,{width:240,margin:2,errorCorrectionLevel:'M'}));setMessage('Show this request only to your intended clinician.');}catch{setMessage('Could not create a request.');}finally{setBusy(false);}}
 return <article className="panel"><h2>Request clinician access</h2><p>A QR is a request, not permission to read your record. After a clinician claims, review their name and the exact sections before allowing access.</p>{sections.map(s=><label key={s} className="check"><input type="checkbox" checked={selected.includes(s)} disabled={busy||pending?.status==='claimed'} onChange={e=>{setSelected(e.target.checked?[...selected,s]:selected.filter(x=>x!==s));setPending(null);setImage('');}}/>{labels[s]}</label>)}<button disabled={busy||!selected.length} onClick={create}>{pending?'Regenerate request':'Create QR request'}</button><p role="status">{message}</p>{pending&&pending.status==='unclaimed'&&seconds>0&&<><img width="240" height="240" src={image} alt="Expiring opaque consent request QR"/><p>Expires in {seconds}s. No medical content or patient ID is in the QR.</p><label>Manual token fallback<textarea readOnly value={pending.token} spellCheck={false}/></label></>}{pending&&pending.status==='claimed'&&<div><h3>Claimed by {pending.clinician_name||'your signed-in clinician'}</h3><p>Requested sections: {pending.sections.map(s=>labels[s]).join(', ')}.</p><p>Display name is not a licensure check. No records shared yet. Allowing gives this clinician only the listed sections for 10 minutes. You can revoke future access from Access & history.</p><button disabled={busy||seconds===0} onClick={approve}>Allow these sections for 10 minutes</button></div>}{pending?.grant&&<div><h3>Approved for {pending.clinician_name}</h3><p>{pending.grant.sections.map(s=>labels[s]).join(', ')} only. Grant status: {pending.grant.status}. Expires at {new Date(pending.grant.expires_at).toLocaleTimeString()}.</p><p>Changing the picker creates a separate request, never widens this grant. Use Access & history to stop future access.</p></div>}{pending&&pending.status!=='approved'&&(seconds===0||pending.status==='expired')&&<p>Request expired. Create a new request.</p>}</article>;
}
