'use client';
import {useEffect,useRef,useState} from 'react';
export default function Scanner(){const [token,setToken]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[scanning,setScanning]=useState(false),video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null);
 function stop(){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(timer.current)clearInterval(timer.current);timer.current=null;setScanning(false);}
 useEffect(()=>()=>{stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearInterval(timer.current);},[]);
 async function camera(){try{const Detector=(window as any).BarcodeDetector;if(!Detector){setStatus('Camera QR scanning is unsupported here. Paste the manual token.');return;}stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});setScanning(true);if(video.current){video.current.srcObject=stream.current;await video.current.play();}const detector=new Detector({formats:['qr_code']});timer.current=setInterval(async()=>{if(!video.current)return;try{const found=await detector.detect(video.current);if(found[0]){setToken(found[0].rawValue);stop();setStatus('QR read. Check the request then tap Claim.');}}catch{stop();setStatus('Scan failed. Use manual token.');}},700);}catch{stop();setStatus('Camera permission denied or unavailable. Use manual token.');}}
 async function claim(){setBusy(true);stop();setStatus('Claiming...');try{const r=await fetch('/api/qr-requests/claim',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:token.trim()}),cache:'no-store'});const d=await r.json();setToken('');if(!r.ok){setStatus(({EXPIRED:'QR expired. Ask for a fresh request.',USED:'QR already claimed. Ask for a fresh request.',RATE_LIMITED:'Too many attempts. Wait a minute.'} as Record<string,string>)[d.error]||'Claim denied. No records received.');return;}setStatus(`Claimed. Waiting for patient approval. No records received. Sections: ${d.sections.join(', ')}. Approval is not implemented in phase 2.`);}catch{setToken('');setStatus('Network unavailable. No records received.');}finally{setBusy(false);}}
 return <article className="panel"><video ref={video} muted playsInline hidden={!scanning} style={{width:'100%',maxHeight:240}}/><div className="row"><button onClick={camera} disabled={busy||scanning}>Scan QR</button>{scanning&&<button onClick={stop}>Stop camera</button>}</div><label>Manual opaque token<textarea value={token} onChange={e=>setToken(e.target.value)} maxLength={43} spellCheck={false}/></label><button onClick={claim} disabled={busy||!token.trim()}>Claim request</button><p role="status">{status}</p></article>;
}
